import { Resend } from 'resend';

export const resend = new Resend(process.env.RESEND_API_KEY!);

export async function sendResumeEmail(email: string, name: string, pdfBuffer: Buffer) {
  try {
    const { data, error } = await resend.emails.send({
      from: `ResumeAI <${process.env.FROM_EMAIL || 'resumes@resend.dev'}>`,
      to: [email],
      subject: `Your ATS-Optimized Resume is Ready! 🎉`,
      html: `
        <div style="font-family: sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; rounded: 10px;">
          <h2 style="color: #4f46e5;">Hello ${name},</h2>
          <p>Great news! Your professional, ATS-optimized resume has been generated and is attached to this email.</p>
          <p><strong>What we optimized:</strong></p>
          <ul>
            <li>Keyword alignment with your target job description.</li>
            <li>Standard ATS-scannable formatting.</li>
            <li>Quantifiable achievement metrics.</li>
            <li>Professional action-oriented language.</li>
          </ul>
          <p>Good luck with your job search! We're rooting for you.</p>
          <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="font-size: 12px; color: #666;">
            Generated by ResumeAI &middot; Beat the ATS. Land the Interview.
          </p>
        </div>
      `,
      attachments: [
        {
          filename: `${name.replace(/\s+/g, '_')}_Resume.pdf`,
          content: pdfBuffer,
        },
      ],
    });

    if (error) {
      console.error("Resend error:", error);
      return { success: false, error };
    }

    return { success: true, data };
  } catch (error) {
    console.error("Email sending failed:", error);
    return { success: false, error };
  }
}
